export type Language = "EN" | "ID";

export const TRANSLATIONS = {
  EN: {
    languageLabel: "Language",
    myWishlist: "My Wishlist",
    chipsHotPicks: "CHIPS Hot Picks",
    newArrival: "New Arrival",
    bestSeller: "Best Seller",
    storeLocations: "Store Locations",
    tel: "Tel",
    searchPlaceholder: "Search Product, Brands, Accessories...",
    searchEmpty: "No matching products found for",
    welcome: "Welcome Back",
    contactUs: "Contact Us",
    allCategories: "All Categories",
    selectIphoneModel: "Filter by iPhone Model:",
    clearAllFilters: "Clear All Filters",
    filteredCatalog: "Filtered Catalog Selection",
    showingItems: "Showing {count} premium items matching your filter.",
    noMatchingProducts: "No Matching Products",
    noMatchingProductsSub: "There are currently no items under this specific segment. Browse other categories.",
    returnToHome: "Return to Home Store",
    bestOfferings: "BEST OFFERINGS THIS WEEK",
    newArrivalsTitle: "New Arrivals",
    newArrivalsSub: "NEW EDITIONS",
    bestSellersTitle: "Best Sellers",
    bestSellersSub: "OVERWHELMINGLY ACCLAIMED",
    officialWarranty: "1 Year Official Warranty",
    officialWarrantySub: "iBox / authorized brand replacement services",
    fastDelivery: "Fast Delivery Nationwide",
    fastDeliverySub: "Delivered to your home in 2-4 hours with security shield",
    easyReturns: "Easy returns within 14 Days",
    easyReturnsSub: "Simply return to one of our branches hassle-free",
    availableInBranches: "Available in Branches",
    addToCart: "ADD TO CART",
    branchLocations: "Branch Locations",
    contactUsTitle: "Contact Us & Support",
    contactUsSub: "GET IN TOUCH WITH OUR AGENTS",
    contactName: "Your Full Name",
    contactEmail: "Email Address",
    contactPhone: "Phone Number",
    contactSubject: "Subject",
    contactMsg: "State your message or inquiry...",
    contactSubmit: "SEND MESSAGE",
    categoryLabel: "Category",
    yourCart: "Your Cart",
    cartEmpty: "Your cart is currently empty",
    totalPrice: "Total Order Price",
    checkout: "PROCEED TO SECURE CHECKOUT",
    wishlistTitle: "My Wishlist",
    wishlistEmpty: "Your wishlist is empty right now",
    brandFilter: "Brand Filter"
  },
  ID: {
    languageLabel: "Bahasa",
    myWishlist: "Keinginan Saya",
    chipsHotPicks: "Produk Rekomendasi",
    newArrival: "Edisi Baru",
    bestSeller: "Sangat Laris",
    storeLocations: "Lokasi Toko",
    tel: "Telp",
    searchPlaceholder: "Cari Produk, Seri iPhone, Laptop...",
    searchEmpty: "Tidak ada produk yang cocok untuk",
    welcome: "Selamat Datang",
    contactUs: "Hubungi Kami",
    allCategories: "Semua Kategori",
    selectIphoneModel: "Pilih Seri iPhone:",
    clearAllFilters: "Hapus Semua Filter",
    filteredCatalog: "Katalog Terfilter",
    showingItems: "Menampilkan {count} produk premium yang sesuai dengan filter.",
    noMatchingProducts: "Produk Tidak Ditemukan",
    noMatchingProductsSub: "Saat ini tidak ada produk di bawah kategori ini. Silakan cari kategori lain.",
    returnToHome: "Kembali ke Beranda",
    bestOfferings: "REKOMENDASI TERBAIK MINGGU INI",
    newArrivalsTitle: "Produk Terbaru",
    newArrivalsSub: "EDISI TERBARU",
    bestSellersTitle: "Paling Laris",
    bestSellersSub: "YANG PALING DIMINATI & TERLARIS",
    officialWarranty: "Garansi Resmi iBox 1 Tahun",
    officialWarrantySub: "Garansi resmi iBox / Mitra brand resmi terpercaya",
    fastDelivery: "Pengiriman Cepat Nasional",
    fastDeliverySub: "Dikirim langsung ke rumah Anda dalam 2-4 jam aman bergaransi",
    easyReturns: "Pengembalian Mudah 14 Hari",
    easyReturnsSub: "Cukup kembalikan ke salah satu toko cabang iBox kami",
    availableInBranches: "Tersedia di Toko Cabang",
    addToCart: "TAMBAH KE KERANJANG",
    branchLocations: "Lokasi Cabang Resmi iBox",
    contactUsTitle: "Dukungan & Hubungi Kami",
    contactUsSub: "TIM AGEN DUKUNGAN PELANGGAN",
    contactName: "Nama Lengkap Anda",
    contactEmail: "Alamat Email",
    contactPhone: "Nomor Telepon",
    contactSubject: "Subjek Pesan",
    contactMsg: "Tuliskan pesan atau pertanyaan Anda di sini...",
    contactSubmit: "KIRIM PESAN SEKARANG",
    categoryLabel: "Kategori",
    yourCart: "Keranjang Belanja",
    cartEmpty: "Keranjang belanja Anda masih kosong",
    totalPrice: "Total Belanjaan",
    checkout: "BAYAR SEKARANG (AMAN)",
    wishlistTitle: "Daftar Keinginan",
    wishlistEmpty: "Daftar keinginan Anda masih kosong",
    brandFilter: "Filter Merek"
  }
};

export function formatProductPrice(priceKD: number, lang: Language): string {
  if (lang === "ID") {
    // Convert to Rupiah, dynamic rate roughly 1 KD = Rp 52.000 for realistic IDR pricing
    const priceIDR = Math.round(priceKD * 52000);
    return `Rp ${priceIDR.toLocaleString("id-ID")}`;
  }
  return `${priceKD.toFixed(3)} KD`;
}
